# General
spring.config.import=optional:file:.env[.properties]
spring.jpa.open-in-view=false

spring.application.name=${SERVICE_NAME:igrp-platform-process-management-studio}
# Default profile
spring.profiles.active=${SPRING_ACTIVE_PROFILE:development}

server.shutdown=graceful

# Observability
otel.resource.attributes.service.name=${spring.application.name}
otel.resource.attributes.deployment.environment=${spring.profiles.active}
otel.logs.exporter=otlp
otel.metrics.exporter=otlp
otel.traces.exporter=otlp
otel.exporter.otlp.endpoint=${OTEL_COLLECTOR_ENDPOINT}
otel.sdk.disabled=${OTEL_DISABLED:true}
